# Generated by Django 5.1.5 on 2025-01-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_create_albums_songs_lines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='length',
            new_name='duration',
        ),
    ]
