# Generated by Django 5.1.5 on 2025-02-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
