name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get -y install make

      - name: Lint files
        run: make linter

      - name: Run containers
        run: make run

      - name: Run tests
        run: make test
